version: '3.8'

services:
  backend:
    build: ./backEnd
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:senha123@db:5432/devopscalc
    volumes:
      - ./backEnd:/app
      - /app/node_modules

  frontend:
    build: ./frontEnd
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontEnd:/usr/share/nginx/html

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: devopscalc
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: