# Uso a imagem oficial do Node.js
FROM node:18

# Defino o diretório de trabalho dentro do container
WORKDIR /app

# Copio os arquivos de dependência primeiro e evito erros
COPY package*.json ./

# Instalando as dependências
RUN npm install

# Copiando o restante do código
COPY . .

# Expondo a porta que o backend usa
EXPOSE 3001

# Comando para rodar a API
CMD ["node", "server.js"]