# Uso a imagem oficial do Node.js
FROM node:18

# Defino o diretório de trabalho dentro do container
WORKDIR /app

# Copio os arquivos do projeto
COPY . .

# Instalando as dependências
RUN npm install

# Expondo a porta que o backend usa
EXPOSE 3001

# Rodando os comandos do migration do prisma e levantando a aplicacao
CMD npx prisma migrate deploy && node server.js